server:
  port: 888

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  redis:
    database: 0
    #host: 127.0.0.1
    host: 106.14.195.35
    #host: localhost
    password: azkj201918
    #password:
  data:
    solr:
      host: http://106.14.195.35:8080/solr
  transaction:
      rollback-on-commit-failure: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql