server:
  port: 717

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


activemq:
  broker-url: tcp://106.14.195.35:61616
  pool:
    enabled: false


spring:
  redis:
    database: 1
    #host: 127.0.0.1
    host: 106.14.195.35
    #host: localhost
    password: azkj201918
    #password:
  transaction:
    rollback-on-commit-failure: true
  servlet:
    multipart:
      #上传一个文件最大值  默认是1MB
      max-file-size: 5MB
      #上传多个文件最大值  默认是10MB
      max-request-size: 20MB
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql