server:
  port: 555

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  redis:
    database: 0
    #host: 127.0.0.1
    host: 106.14.195.35
    #host: localhost
    password: azkj201918
    #password:
